users:
  AAK:
    password: "AAK_Detachlog_25"  # change manually every 3 months
  BarryC:
    password: "BarryC_Detachlog_25"  # change manually every 3 months
  Aasted:
    password: "Aasted_Detachlog_25"  # change manually every 3 months

